{% set name = "palmari" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/palmari-{{ version }}.tar.gz
  sha256: e55e7b74a09243104159241f8d30f4a820704e0d7466f3a44f9d926d775ed709

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - click
    - dask-core >=2022.1.0
    - dask-image >=2021.12.0
    - imageio-ffmpeg
    - magicgui >=0.5.0
    - matplotlib-base >=3.5
    - munkres
    - napari
    - napari-aicsimageio
    - numpy
    - pandas
    - python >={{ python_min }}
    - pyyaml
    - qtpy
    - scikit-image >=0.18.3
    - scikit-learn
    - toml
    - tqdm
    - trackpy >=0.5.0

test:
  imports:
    - palmari
  commands:
    - pip list
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/hippover/palmari
  summary: A pipeline for PALM movies analysis (pre-processing, localization, drifft correction, tracking)
  license: LGPL-2.1-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - hippover
    - jaimergp
